# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-21 17:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('staff_id', models.UUIDField(primary_key=True, serialize=False)),
                ('company_id', models.UUIDField()),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('documents', models.FileField(upload_to='documents')),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
